### ISSUE TITLE
所需数据库的最低版本是

### ISSUE THREAD

**Issue by jkjoy** [pjblog/blog#4]
服务器centos7.9 MySQL的版本5.6
安装不成功。
本地macos下测试
 MySQL8.0安装成功

**Comment by cevio** [comment]
@jkjoy https://github.com/pjblog/blog/issues/4#issue-1620983538

这个问题在于我们没有测试mongodb，mysql是没问题的。

修正版本和全系统可hook版本正在开发中。https://github.com/pjblog/blog/tree/next 从这里你可以参考
